/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::realtime::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AddTranscript {
    /// Speechmatics JSON output format version number.
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(rename = "message")]
    pub message: Message,
    #[serde(rename = "metadata")]
    pub metadata: Box<models::RecognitionMetadata>,
    #[serde(rename = "results")]
    pub results: Vec<models::RecognitionResult>,
}

impl AddTranscript {
    pub fn new(message: Message, metadata: models::RecognitionMetadata, results: Vec<models::RecognitionResult>) -> AddTranscript {
        AddTranscript {
            format: None,
            message,
            metadata: Box::new(metadata),
            results,
        }
    }
}
/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Message {
    #[serde(rename = "AddTranscript")]
    AddTranscript,
}

impl Default for Message {
    fn default() -> Message {
        Self::AddTranscript
    }
}

