/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AudioAdded {
    #[serde(rename = "message")]
    pub message: Message,
    #[serde(rename = "seq_no")]
    pub seq_no: i32,
}

impl AudioAdded {
    pub fn new(message: Message, seq_no: i32) -> AudioAdded {
        AudioAdded {
            message,
            seq_no,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Message {
    #[serde(rename = "AudioAdded")]
    AudioAdded,
}

impl Default for Message {
    fn default() -> Message {
        Self::AudioAdded
    }
}

