/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::realtime::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DiarizationConfig {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "speaker")]
    Speaker,
    #[serde(rename = "speaker_change")]
    SpeakerChange,

}

impl std::fmt::Display for DiarizationConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::None => write!(f, "none"),
            Self::Speaker => write!(f, "speaker"),
            Self::SpeakerChange => write!(f, "speaker_change"),
        }
    }
}

impl Default for DiarizationConfig {
    fn default() -> DiarizationConfig {
        Self::None
    }
}

