/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct EndOfTranscript {
    #[serde(rename = "message")]
    pub message: Message,
}

impl EndOfTranscript {
    pub fn new(message: Message) -> EndOfTranscript {
        EndOfTranscript {
            message,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Message {
    #[serde(rename = "EndOfTranscript")]
    EndOfTranscript,
}

impl Default for Message {
    fn default() -> Message {
        Self::EndOfTranscript
    }
}

