/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::realtime::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MaxDelayModeConfig {
    #[serde(rename = "flexible")]
    Flexible,
    #[serde(rename = "fixed")]
    Fixed,

}

impl std::fmt::Display for MaxDelayModeConfig {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Flexible => write!(f, "flexible"),
            Self::Fixed => write!(f, "fixed"),
        }
    }
}

impl Default for MaxDelayModeConfig {
    fn default() -> MaxDelayModeConfig {
        Self::Flexible
    }
}

