/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OperatingPoint {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "enhanced")]
    Enhanced,

}

impl ToString for OperatingPoint {
    fn to_string(&self) -> String {
        match self {
            Self::Standard => String::from("standard"),
            Self::Enhanced => String::from("enhanced"),
        }
    }
}

impl Default for OperatingPoint {
    fn default() -> OperatingPoint {
        Self::Standard
    }
}




