/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RecognitionDisplay {
    #[serde(rename = "direction")]
    pub direction: Direction,
}

impl RecognitionDisplay {
    pub fn new(direction: Direction) -> RecognitionDisplay {
        RecognitionDisplay {
            direction,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Direction {
    #[serde(rename = "ltr")]
    Ltr,
    #[serde(rename = "rtl")]
    Rtl,
}

impl Default for Direction {
    fn default() -> Direction {
        Self::Ltr
    }
}

