/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RecognitionStarted {
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,
    #[serde(rename = "message")]
    pub message: Message,
}

impl RecognitionStarted {
    pub fn new(message: Message) -> RecognitionStarted {
        RecognitionStarted {
            id: None,
            message,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Message {
    #[serde(rename = "RecognitionStarted")]
    RecognitionStarted,
}

impl Default for Message {
    fn default() -> Message {
        Self::RecognitionStarted
    }
}

