/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RecognitionMetadata {
    #[serde(rename = "end_time")]
    pub end_time: f32,
    #[serde(rename = "start_time")]
    pub start_time: f32,
    #[serde(rename = "transcript")]
    pub transcript: String,
}

impl RecognitionMetadata {
    pub fn new(end_time: f32, start_time: f32, transcript: String) -> RecognitionMetadata {
        RecognitionMetadata {
            end_time,
            start_time,
            transcript,
        }
    }
}


