/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SpeakerDiarizationConfig {
    #[serde(rename = "max_speakers", skip_serializing_if = "Option::is_none")]
    pub max_speakers: Option<f32>,
}

impl SpeakerDiarizationConfig {
    pub fn new() -> SpeakerDiarizationConfig {
        SpeakerDiarizationConfig {
            max_speakers: None,
        }
    }
}


