/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TranslatedSentence {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "end_time")]
    pub end_time: f32,
    #[serde(rename = "speaker", skip_serializing_if = "Option::is_none")]
    pub speaker: Option<String>,
    #[serde(rename = "start_time")]
    pub start_time: f32,
}

impl TranslatedSentence {
    pub fn new(content: String, end_time: f32, start_time: f32) -> TranslatedSentence {
        TranslatedSentence {
            content,
            end_time,
            speaker: None,
            start_time,
        }
    }
}


