/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TranslationConfig {
    #[serde(rename = "enable_partials", skip_serializing_if = "Option::is_none")]
    pub enable_partials: Option<bool>,
    #[serde(rename = "target_languages")]
    pub target_languages: Vec<String>,
}

impl TranslationConfig {
    pub fn new(target_languages: Vec<String>) -> TranslationConfig {
        TranslationConfig {
            enable_partials: None,
            target_languages,
        }
    }
}


