/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::realtime::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum VocabWord {
    VocabWordOneOf(Box<models::VocabWordOneOf>),
    String(String),
}

impl Default for VocabWord {
    fn default() -> Self {
        VocabWord::VocabWordOneOf(Box::new(models::VocabWordOneOf::default()))
    }
}
