/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct VocabWord {
    #[serde(rename = "content")]
    pub content: String,
    #[serde(rename = "sounds_like", skip_serializing_if = "Option::is_none")]
    pub sounds_like: Option<Vec<String>>,
}

impl VocabWord {
    pub fn new(content: String) -> VocabWord {
        VocabWord {
            content,
            sounds_like: None,
        }
    }
}


