/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DiarizationConfig {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "speaker")]
    Speaker,
    #[serde(rename = "speaker_change")]
    SpeakerChange,

}

impl ToString for DiarizationConfig {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("none"),
            Self::Speaker => String::from("speaker"),
            Self::SpeakerChange => String::from("speaker_change"),
        }
    }
}

impl Default for DiarizationConfig {
    fn default() -> DiarizationConfig {
        Self::None
    }
}




