/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RealtimeMessage {
    #[serde(rename = "message", skip_serializing_if = "Option::is_none")]
    pub message: Option<crate::realtime::models::Messages>,
}

impl RealtimeMessage {
    pub fn new() -> RealtimeMessage {
        RealtimeMessage {
            message: None,
        }
    }
}


