/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct DataFetchConfig {
    #[serde(rename = "url")]
    pub url: String,
    /// A list of additional headers to be added to the input fetch request when using http or https. This is intended to support authentication or authorization, for example by supplying an OAuth2 bearer token.
    #[serde(rename = "auth_headers", skip_serializing_if = "Option::is_none")]
    pub auth_headers: Option<Vec<String>>,
}

impl DataFetchConfig {
    pub fn new(url: String) -> DataFetchConfig {
        DataFetchConfig {
            url,
            auth_headers: None,
        }
    }
}


