/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobType {
    #[serde(rename = "transcription")]
    Transcription,
    #[serde(rename = "alignment")]
    Alignment,

}

impl ToString for JobType {
    fn to_string(&self) -> String {
        match self {
            Self::Transcription => String::from("transcription"),
            Self::Alignment => String::from("alignment"),
        }
    }
}

impl Default for JobType {
    fn default() -> JobType {
        Self::Transcription
    }
}




