/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */

use crate::batch::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobType {
    #[serde(rename = "transcription")]
    Transcription,
    #[serde(rename = "alignment")]
    Alignment,

}

impl std::fmt::Display for JobType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Transcription => write!(f, "transcription"),
            Self::Alignment => write!(f, "alignment"),
        }
    }
}

impl Default for JobType {
    fn default() -> JobType {
        Self::Transcription
    }
}

