/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum JobMode {
    #[serde(rename = "batch")]
    Batch,

}

impl ToString for JobMode {
    fn to_string(&self) -> String {
        match self {
            Self::Batch => String::from("batch"),
        }
    }
}

impl Default for JobMode {
    fn default() -> JobMode {
        Self::Batch
    }
}




