/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */

use crate::batch::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OperatingPoint {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "enhanced")]
    Enhanced,

}

impl std::fmt::Display for OperatingPoint {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Standard => write!(f, "standard"),
            Self::Enhanced => write!(f, "enhanced"),
        }
    }
}

impl Default for OperatingPoint {
    fn default() -> OperatingPoint {
        Self::Standard
    }
}

