/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */

use crate::batch::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct OutputConfig {
    #[serde(rename = "srt_overrides", skip_serializing_if = "Option::is_none")]
    pub srt_overrides: Option<Box<models::OutputConfigSrtOverrides>>,
}

impl OutputConfig {
    pub fn new() -> OutputConfig {
        OutputConfig {
            srt_overrides: None,
        }
    }
}

