/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */

use crate::batch::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RetrieveJobsResponse {
    #[serde(rename = "jobs")]
    pub jobs: Vec<models::JobDetails>,
}

impl RetrieveJobsResponse {
    pub fn new(jobs: Vec<models::JobDetails>) -> RetrieveJobsResponse {
        RetrieveJobsResponse {
            jobs,
        }
    }
}

