/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */

/// SentimentSpeakerSummary : Holds sentiment information for a specific speaker.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct SentimentSpeakerSummary {
    #[serde(rename = "speaker", skip_serializing_if = "Option::is_none")]
    pub speaker: Option<String>,
    #[serde(rename = "positive_count", skip_serializing_if = "Option::is_none")]
    pub positive_count: Option<i32>,
    #[serde(rename = "negative_count", skip_serializing_if = "Option::is_none")]
    pub negative_count: Option<i32>,
    #[serde(rename = "neutral_count", skip_serializing_if = "Option::is_none")]
    pub neutral_count: Option<i32>,
}

impl SentimentSpeakerSummary {
    /// Holds sentiment information for a specific speaker.
    pub fn new() -> SentimentSpeakerSummary {
        SentimentSpeakerSummary {
            speaker: None,
            positive_count: None,
            negative_count: None,
            neutral_count: None,
        }
    }
}


