/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */

use crate::batch::models;
use serde::{Deserialize, Serialize};

/// SentimentSummaryDetail : Holds the count of sentiment information grouped by positive, neutral and negative.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SentimentSummaryDetail {
    #[serde(rename = "positive_count", skip_serializing_if = "Option::is_none")]
    pub positive_count: Option<i32>,
    #[serde(rename = "negative_count", skip_serializing_if = "Option::is_none")]
    pub negative_count: Option<i32>,
    #[serde(rename = "neutral_count", skip_serializing_if = "Option::is_none")]
    pub neutral_count: Option<i32>,
}

impl SentimentSummaryDetail {
    /// Holds the count of sentiment information grouped by positive, neutral and negative.
    pub fn new() -> SentimentSummaryDetail {
        SentimentSummaryDetail {
            positive_count: None,
            negative_count: None,
            neutral_count: None,
        }
    }
}

