/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */

/// TranscriptionConfigPunctuationOverrides : Control punctuation settings.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TranscriptionConfigPunctuationOverrides {
    /// Ranges between zero and one. Higher values will produce more punctuation. The default is 0.5.
    #[serde(rename = "sensitivity", skip_serializing_if = "Option::is_none")]
    pub sensitivity: Option<f32>,
    /// The punctuation marks which the client is prepared to accept in transcription output, or the special value 'all' (the default). Unsupported marks are ignored. This value is used to guide the transcription process.
    #[serde(rename = "permitted_marks", skip_serializing_if = "Option::is_none")]
    pub permitted_marks: Option<Vec<String>>,
}

impl TranscriptionConfigPunctuationOverrides {
    /// Control punctuation settings.
    pub fn new() -> TranscriptionConfigPunctuationOverrides {
        TranscriptionConfigPunctuationOverrides {
            sensitivity: None,
            permitted_marks: None,
        }
    }
}


