/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */

/// TranscriptionConfigSpeakerDiarizationConfig : Configuration for speaker diarization



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TranscriptionConfigSpeakerDiarizationConfig {
    /// Controls how sensitive the algorithm is in terms of keeping similar speakers separate, as opposed to combining them into a single speaker.  Higher values will typically lead to more speakers, as the degree of difference between speakers in order to allow them to remain distinct will be lower.  A lower value for this parameter will conversely guide the algorithm towards being less sensitive in terms of retaining similar speakers, and as such may lead to fewer speakers overall.  The default is 0.5.
    #[serde(rename = "speaker_sensitivity", skip_serializing_if = "Option::is_none")]
    pub speaker_sensitivity: Option<f32>,
}

impl TranscriptionConfigSpeakerDiarizationConfig {
    /// Configuration for speaker diarization
    pub fn new() -> TranscriptionConfigSpeakerDiarizationConfig {
        TranscriptionConfigSpeakerDiarizationConfig {
            speaker_sensitivity: None,
        }
    }
}


