/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum OperatingPoint {
    #[serde(rename = "standard")]
    Standard,
    #[serde(rename = "enhanced")]
    Enhanced,

}

impl ToString for OperatingPoint {
    fn to_string(&self) -> String {
        match self {
            Self::Standard => String::from("standard"),
            Self::Enhanced => String::from("enhanced"),
        }
    }
}

impl Default for OperatingPoint {
    fn default() -> OperatingPoint {
        Self::Standard
    }
}




