/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */

/// OutputConfigSrtOverrides : Parameters that override default values of srt conversion. max_line_length: sets maximum count of characters per subtitle line including white space. max_lines: sets maximum count of lines in a subtitle section.



#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct OutputConfigSrtOverrides {
    #[serde(rename = "max_line_length", skip_serializing_if = "Option::is_none")]
    pub max_line_length: Option<i32>,
    #[serde(rename = "max_lines", skip_serializing_if = "Option::is_none")]
    pub max_lines: Option<i32>,
}

impl OutputConfigSrtOverrides {
    /// Parameters that override default values of srt conversion. max_line_length: sets maximum count of characters per subtitle line including white space. max_lines: sets maximum count of lines in a subtitle section.
    pub fn new() -> OutputConfigSrtOverrides {
        OutputConfigSrtOverrides {
            max_line_length: None,
            max_lines: None,
        }
    }
}


