/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct TranslationConfig {
    /// Array of ISO language codes that you would like your audio to be translated into.
    #[serde(rename = "target_languages")]
    pub target_languages: Vec<String>,
}

impl TranslationConfig {
    pub fn new(target_languages: Vec<String>) -> TranslationConfig {
        TranslationConfig {
            target_languages,
        }
    }
}


