/*
 * Speechmatics ASR REST API
 *
 * The Speechmatics Automatic Speech Recognition REST API is used to submit ASR jobs and receive the results. 
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@speechmatics.com
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct UsageResponse {
    #[serde(rename = "since")]
    pub since: String,
    #[serde(rename = "until")]
    pub until: String,
    #[serde(rename = "summary")]
    pub summary: Vec<crate::batch::models::UsageDetails>,
    #[serde(rename = "details")]
    pub details: Vec<crate::batch::models::UsageDetails>,
}

impl UsageResponse {
    pub fn new(since: String, until: String, summary: Vec<crate::batch::models::UsageDetails>, details: Vec<crate::batch::models::UsageDetails>) -> UsageResponse {
        UsageResponse {
            since,
            until,
            summary,
            details,
        }
    }
}


