/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddPartialTranslation {
    /// Speechmatics JSON output format version number.
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(rename = "language")]
    pub language: String,
    #[serde(rename = "message")]
    pub message: Message,
    #[serde(rename = "results")]
    pub results: Vec<crate::realtime::models::TranslatedSentence>,
}

impl AddPartialTranslation {
    pub fn new(language: String, message: Message, results: Vec<crate::realtime::models::TranslatedSentence>) -> AddPartialTranslation {
        AddPartialTranslation {
            format: None,
            language,
            message,
            results,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Message {
    #[serde(rename = "AddPartialTranslation")]
    AddPartialTranslation,
}

impl Default for Message {
    fn default() -> Message {
        Self::AddPartialTranslation
    }
}

