/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */




#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct AddPartialTranscript {
    /// Speechmatics JSON output format version number.
    #[serde(rename = "format", skip_serializing_if = "Option::is_none")]
    pub format: Option<String>,
    #[serde(rename = "message")]
    pub message: Message,
    #[serde(rename = "metadata")]
    pub metadata: Box<crate::realtime::models::RecognitionMetadata>,
    #[serde(rename = "results")]
    pub results: Vec<crate::realtime::models::RecognitionResult>,
}

impl AddPartialTranscript {
    pub fn new(message: Message, metadata: crate::realtime::models::RecognitionMetadata, results: Vec<crate::realtime::models::RecognitionResult>) -> AddPartialTranscript {
        AddPartialTranscript {
            format: None,
            message,
            metadata: Box::new(metadata),
            results,
        }
    }
}

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Message {
    #[serde(rename = "AddPartialTranscript")]
    AddPartialTranscript,
}

impl Default for Message {
    fn default() -> Message {
        Self::AddPartialTranscript
    }
}

