/*
 * OpenAPI Template
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MaxDelayModeConfig {
    #[serde(rename = "flexible")]
    Flexible,
    #[serde(rename = "fixed")]
    Fixed,

}

impl ToString for MaxDelayModeConfig {
    fn to_string(&self) -> String {
        match self {
            Self::Flexible => String::from("flexible"),
            Self::Fixed => String::from("fixed"),
        }
    }
}

impl Default for MaxDelayModeConfig {
    fn default() -> MaxDelayModeConfig {
        Self::Flexible
    }
}




