

name: "Test"

on: 
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  check:
    name: "Cargo check"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          command: "cargo check"

  test:
    name: "Cargo test"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3

      - uses: "dtolnay/rust-toolchain@stable"
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true

      - uses: dtolnay/rust-toolchain@stable
        with:
          command: "cargo test"
        env:
          API_KEY: ${{ secrets.API_KEY }}

  fmt:
    name: "Cargo format"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true
          
      - run: "rustup component add rustfmt"

      - uses: dtolnay/rust-toolchain@stable
        with:
          command: "cargo fmt"
          args: "--all -- --check"

  clippy:
    name: "Cargo clippy"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out the repo"
        uses: actions/checkout@v3

      - uses: dtolnay/rust-toolchain@stable
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true

      - run: "rustup component add clippy"

      - uses: dtolnay/rust-toolchain@stable
        with:
          command: "rustup clippy"
          args: "-- -D warnings"

